package:
  name: cvxopt_glpk
  version: 1.1.8

source:
  git_url: https://github.com/cvxopt/cvxopt.git
  git_tag: 1.1.8

build:
  number: 0

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - cvxopt
    - cvxopt.misc
    - cvxopt.glpk

about:
  home: http://cvxopt.org/
  license: GPL v3
  summary: Python Software for Convex Optimization
