package:
  name: artview
  version: "1.2"

source:
  git_url: https://github.com/nguy/artview
  git_rev: v1.2

build:
  number: 0

requirements:
  build:
    - python
    - pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6
  run:
    - python
    - pyart >=1.5
    - matplotlib >=1.1
    - pyqt >=4.6

test:
  imports:
    - artview

about:
  home: https://github.com/nguy/artview
  license: BSD
  summary: ARM Radar Toolkit Viewer

extra:
  recipe-maintainers:
    - jjhelmus
