{% set version = "3.0.2" %}

package:
    name: pyamg
    version: {{ version }}

source:
    fn: pyamg-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/pyamg/pyamg-{{ version }}.tar.gz
    md5: bd024253ebae6f7bf2d89fe32fc5d64a

build:
    number: 0

requirements:
    build:
        - python
        - numpy x.x
        - scipy
        - zlib  # [linux]
    run:
        - python
        - numpy x.x
        - scipy
        - zlib  # [linux]

test:
    requires:
        - nose
    imports:
        - pyamg
    commands:
        - python -c "import pyamg; pyamg.test()"

about:
    home: https://github.com/pyamg/pyamg
    license: BSD
    summary: "PyAMG: Algebraic Multigrid Solvers in Python"

extra:
    recipe-maintainers:
        - jjhelmus
