FROM condaforge/linux-anvil

MAINTAINER Jonathan J. Helmus <jjhelmus@gmail.com>

# Install additional yum packages needed for bazel/tensorflow
RUN yum install -y java-1.8.0-openjdk-devel 
RUN yum install -y unzip zip zlib-devel rsync
