package:
  name: feather-format
  version: "0.1.0"

source:
  fn: feather-format-0.1.0.tar.gz
  url: https://pypi.python.org/packages/source/f/feather-format/feather-format-0.1.0.tar.gz
  md5: ae2a99f4c14088787d73a6050e3a77a8

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - cython
    - pandas >=0.17.0
  run:
    - python
    - pandas >=0.17.0

test:
  imports:
    - feather

about:
  home: https://github.com/wesm/feather 
  license: Apache 2.0
  summary: "Feather: fast, interoperable binary data frame storage for Python, R, and more powered by Apache Arrow"

extra:
  recipe-maintainers:
    - jjhelmus
